name: a2
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Some value'
        required: true
        default: 'the default value'

jobs:
  say_hello:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        echo blah blah blah ${{ github.event.inputs.name }} blah blah blah
