name: Draw Sierpinski triangle
on:
  worflow_dispatch:
    inputs:
      name: iters
      description: Number of iterations
      default: 4
jobs:
  draw_the_triangle:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        function rec(){
          if [ $1 == 0 ]
          then 
            echo "x"
          else
            rec $[ $1 - 1 ] | while read line ; do 
              echo "$line" | sed "s/d/dd/g" | sed "s/x/dxd/g"
              echo "$line" | sed "s/d/dd/g" | sed "s/x/xsx/g"
            done
          fi
        }
        rec ${{ github.event.inputs.iters }} | tr 'dsx' '  *'
